<a href="https://colab.research.google.com/github/Biancaa-R/Matrices-Determinats/blob/main/Matrices%2CDeterminants_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#matrice multiplication using numpy

In [9]:
#matrice multiplication using numpy
#vectorised implimentation

import numpy as np
A=[[1,2,3],
[4,5,6],
[7,8,9]]

B=[[10,11,12],
[13,14,15],
[16,17,18]]

result=[[0,0,0],
[0,0,0],
[0,0,0]]

result=np.dot(A,B)
for r in result:
  print(r)

[84 90 96]
[201 216 231]
[318 342 366]


# Matrice multiplication using nested loops

In [10]:
#Multiplication using nested loops

A=[[19,20,21],
[22,23,24],
[25,26,27]]

B=[[28,29,30],
[31,32,33],
[34,35,36]]

result=[[0,0,0],
[0,0,0],
[0,0,0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] +=A[i][k]* B[k][j]

for r in result:
    print(r)




[1866, 1926, 1986]
[2145, 2214, 2283]
[2424, 2502, 2580]


#Finding the transpose of a matrice using nested loop

In [12]:
# Program to transpose a matrix using a nested loop

X = [[12,7,6],
[4 ,5,9],
[3 ,8,5]]

result = [[0,0,0],
[0,0,0],
[0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)

[12, 4, 3]
[7, 5, 8]
[6, 9, 5]


# Transpose with list

In [16]:
''' Program to transpose a matrix using list comprehension'''

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]

for r in result:
   print(r)
   

[12, 4, 3]
[7, 5, 8]


**explanion**:

here range values of j determines the number of coloumns and the range values of i determines the number of rows.
```
# This is formatted as code
result=[[X[j][i] for j in range len(X)] for i in range len(X[0])
```
length of X=3

range(3)=0,1,2

length of X[0]=2

range(2)=1,2

**List one ****:

case1:

 j=0,i=0 therefore result= X[0][0]=12

case2:

j=1,i=0 therefore result=X[1][0]=4

case3:

j=2,i=0 therefore result X[2][0]=3

There is no more possible iteration of j so list one over

result=[12,4,3]

**list 2**

case1:

j=0,i=1 therefore result X[0][1]=7

case2:

j=1,i=1 therefore result X[1][1]=5


case3::
j=2, i=1 therefore result X[2][1]=8

no more possible iterations of j so list 2 over

result=[12,4,3],
       [7,5,8]

```
# This is formatted as code
for r in result:
   print(r)
```
This prints : 

 [12,4,3]

[7,5,8]





